### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [Ivan-Kalatchev/BootstrapExtended#3]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by Ivan-Kalatchev** [comment]
Greetings 👋🏻,

Yes, the project is very much active. I just haven't had much time lately to work on it. If you have any plans or ideas about it, I would be more then happy to see and merge them 👍🏻.

PS. I apologise for the late response. I have been sick for the past week or two.

**Comment by ghost** [comment]
Hi Ivan-Kalatchev.

> Greetings 👋🏻,
> Yes, the project is very much active. I just haven't had much time lately to work on it. If you have any plans or ideas about it, I would be more then happy to see and merge them 👍🏻.
> PS. I apologise for the late response. I have been sick for the past week or two.

thank you for feedback and information here now.
